Models/Accommodation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace BookingApp.Models
{
    public class Accommodation
    {
		public Guid Id { get; set; }

		public string UserId { get; set; }

		[Display(Name = "Utilisateur")]
		[JsonIgnore]
		public virtual User User { get; set; }

		[Display(Name = "Offres")]
		[JsonIgnore]
		public virtual List<Offer> Offers { get; set; }

		[Display(Name = "Adresse")]
		public virtual Address Address { get; set; }

		[Display(Name = "Règlement intérieur")]
		public virtual HouseRules HouseRules { get; set; }

		[Display(Name = "Photo(s)")]
		public virtual List<Picture> Pictures { get; set; }

		[Display(Name = "Pièce(s)")]
		public virtual List<Room> Rooms { get; set; }

		[Required(ErrorMessage = "Vous devez entrer un nom pour votre logement")]
		[Display(Name = "Nom")]
		public String Name { get; set; }

		[Required(ErrorMessage = "Vous devez sélectionner le type du logement")]
		[Display(Name = "Type")]
		[RegularExpression("Appartement|Maison|Chambre dans un appartement|Chambre dans une maison", 
			ErrorMessage = "Veuillez sélectionner un type de logement valide")]
		public String Type { get; set; }

		[Required(ErrorMessage = "Vous devez indiquer le nombre maximum de voyageurs")]
		[Display(Name = "Maximum Voyageurs")]
		public int MaxTraveler { get; set; }

		[Required(ErrorMessage = "Vous devez entrer la description de votre logement")]
		public String Description { get; set; }
	}
}

Controllers/AmenityController.cs
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookingApp.Controllers
{
    [Route("Accommodation")]
    public class AmenityController : Controller
    {
        private readonly AppContextDB _context;

        public AmenityController(AppContextDB context)
        {
            _context = context;
        }

        // GET: Accommodation/ManageAmenities/5
        [Route("ManageAmenities/{roomId:guid?}")]
        public async Task<IActionResult> ManageAmenities(Guid? roomId)
        {
            if (roomId == null) { return NotFound(); }

            var room = await _context.Rooms
                .Include(r => r.Amenities)
                .FirstOrDefaultAsync(r => r.Id == roomId);

            if (room == null) { return NotFound(); }

            if (TempData["AlertType"] != null && TempData["AlertMsg"] != null)
            {
                ViewBag.AlertType = TempData["AlertType"];
                ViewBag.AlertMsg = TempData["AlertMsg"];
            }

            string roomType = room.RoomType.ToString();

            ViewBag.AmenityTypes = AmenityTools.AmenitiesForRoom(roomType);

            return View(room);
        }

        // POST: Accommodation/AddAmenity/5
        [HttpPost]
        [Route("AddAmenity/{roomId:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAmenity(Guid roomId, string amenityType)
        {
            var room = await _context.Rooms
                .Include(r => r.Amenities)
                .FirstOrDefaultAsync(r => r.Id == roomId);

            if (room == null) { return NotFound(); }

            List<string> amenityTypes = AmenityTools.AmenitiesForRoom(room.RoomType.ToString());

            if (amenityTypes.Contains(amenityType))
            {
                room.Amenities.Add(new Amenity { AmenityType = (AmenityTypes)Enum.Parse(typeof(AmenityTypes), amenityType, true) });
                _context.Update(room);
                await _context.SaveChangesAsync();
            }
            else
            {
                TempData["AlertType"] = "warning";
                TempData["AlertMsg"] = "Equipement non valide !";
            }

            return RedirectToAction("ManageAmenities", new { roomId });
        }

        // POST: Accommodation/DeleteAmenity/5
        [HttpPost]
        [Route("DeleteAmenity/{amenityId:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAmenity(Guid amenityId, Guid roomId)
        {
            var nbAmenities = await _context.Amenity.CountAsync(r => r.RoomId == roomId);

            if (nbAmenities > 1)
            {
                var amenity = await _context.Amenity.FindAsync(amenityId);

                _context.Amenity.Remove(amenity);
                await _context.SaveChangesAsync();
            }
            else
            {
                TempData["AlertType"] = "warning";
                TempData["AlertMsg"] = "Une pièce doit contenir au moins 1 équipement !";
            }

            return RedirectToAction("ManageAmenities", new { roomId });
        }
    }
}

Controllers/PictureController.cs
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace BookingApp.Views.Accommodation
{
    [Route("Accommodation")]
    public class PictureController : Controller
    {
        private readonly AppContextDB _context;
        private readonly IWebHostEnvironment _environment;

        public PictureController(AppContextDB context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Accommodation/ManagePictures/5
        [Route("ManagePictures/{id:guid?}")]
        public async Task<IActionResult> ManagePictures(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accommodation = await _context.Accommodations
                .Include(a => a.Pictures)
                .Include(a => a.Rooms)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (accommodation == null)
            {
                return NotFound();
            }

            if (accommodation.Pictures.Count == 0)
            {
                ViewBag.AlertType = "warning";
                ViewBag.AlertMsg = "Veuillez ajouter au moins une photo à votre logement !";
            }

            if (TempData["AlertType"] != null && TempData["AlertMsg"] != null)
            {
                ViewBag.AlertType = TempData["AlertType"];
                ViewBag.AlertMsg = TempData["AlertMsg"];
            }

            return View(accommodation);
        }

        // POST: Accommodation/ManagePictures/5
        [HttpPost]
        [Route("ManagePictures/{id:guid?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManagePictures(Guid? id, List<IFormFile> files)
        {
            if (id == null)
            {
                return NotFound();
            }

            Directory.CreateDirectory(Path.Combine(_environment.WebRootPath, "upload"));

            foreach (var formFile in files)
            {
                if (await _context.Pictures.CountAsync(p => p.AccommodationId == (Guid)id) == 12)
                {
                    TempData["AlertType"] = "danger";
                    TempData["AlertMsg"] = "Vous avez atteint le nombre maximum de photos ! Une ou plusieurs photos n'ont pas pu être ajoutées.";
                    
                    return RedirectToAction("ManagePictures", new { id });
                }

                if (formFile.Length > 0)
                {
                    string fileName = DateTime.Now.ToString("ddMMyyyyHHmmssfff") + "_" + Guid.NewGuid().ToString("N")
                        + Path.GetExtension(formFile.FileName);

                    string filePath = Path.Combine(_environment.WebRootPath, "upload", fileName);

                    using var stream = System.IO.File.Create(filePath);
                    await formFile.CopyToAsync(stream);

                    await _context.Pictures.AddAsync(new Picture((Guid)id, fileName));
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction("ManagePictures", new { id });
        }

        // GET: Accommodation/DeletePicture/5
        [Route("DeletePicture/{id:guid}")]
        public async Task<IActionResult> DeletePicture(Guid id, Guid accommodationId)
        {
            // TODO: Check if user own the picture
            var picture = await _context.Pictures.FindAsync(id);

            string filePath = Path.Combine(_environment.WebRootPath, "upload", picture.FileName);

            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }

            _context.Pictures.Remove(picture);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManagePictures", new { id = accommodationId });
        }
    }
}

Controllers/RoomController.cs
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookingApp.Controllers
{
    public class RoomController : Controller
    {
        private readonly AppContextDB _context;

        public RoomController(AppContextDB context)
        {
            _context = context;
        }

        // GET: Accommodation/ManageRooms/5
        [Route("Accommodation/ManageRooms/{id?}")]
        public async Task<IActionResult> ManageRooms(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accommodation = await _context.Accommodations
                .Include(a => a.Pictures)
                .Include(a => a.Rooms)
                .ThenInclude(r => r.Amenities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (accommodation == null)
            {
                return NotFound();
            }

            if (accommodation.Rooms.Count == 0)
            {
                ViewBag.AlertType = "warning";
                ViewBag.AlertMsg = "Veuillez ajouter au moins une pièce à votre logement !";
            }

            return View(accommodation);
        }


        // POST: Accommodation/ManageRooms/5
        [HttpPost]
        [Route("Accommodation/ManageRooms/{id?}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRooms(Guid? accommodationId, string roomType,
            string singleBedNumber, string doubleBedNumber, string tv, string closet,
            string bathtub, string shower, string washingMachine,
            string oven, string freezer, string coffeeMaker)
        {
            if (accommodationId == null)
            {
                return NotFound();
            }

            List<Amenity> amenities = new();

            switch (roomType)
            {
                case "Bedroom":
                    if (tv == null && closet == null && (singleBedNumber == null || int.Parse(singleBedNumber) == 0) && (doubleBedNumber == null || int.Parse(doubleBedNumber) == 0))
                    {
                        ViewBag.AlertType = "danger";
                        ViewBag.AlertMsg = "Veuillez ajouter au moins un équipement à votre pièce !";
                    }
                    else
                    {
                        AddMultipleAmenities(amenities, singleBedNumber, "SingleBed");
                        AddMultipleAmenities(amenities, doubleBedNumber, "DoubleBed");

                        AddAmenityIfChecked(amenities, tv, "TV");
                        AddAmenityIfChecked(amenities, closet, "Closet");

                        await SaveRoom((Guid)accommodationId, roomType, amenities);
                    }

                    break;

                case "Bathroom":
                    if (bathtub == null && shower == null && washingMachine == null)
                    {
                        ViewBag.AlertType = "danger";
                        ViewBag.AlertMsg = "Veuillez ajouter au moins un équipement à votre pièce !";
                    } 
                    else
                    {
                        AddAmenityIfChecked(amenities, bathtub, "Bathtub");
                        AddAmenityIfChecked(amenities, shower, "Shower");
                        AddAmenityIfChecked(amenities, washingMachine, "WashingMachine");

                        await SaveRoom((Guid)accommodationId, roomType, amenities);
                    }

                    break;

                case "Kitchen":
                    if (oven == null && freezer == null && coffeeMaker == null)
                    {
                        ViewBag.AlertType = "danger";
                        ViewBag.AlertMsg = "Veuillez ajouter au moins un équipement à votre pièce !";
                    } 
                    else
                    {
                        AddAmenityIfChecked(amenities, oven, "Oven");
                        AddAmenityIfChecked(amenities, freezer, "Freezer");
                        AddAmenityIfChecked(amenities, coffeeMaker, "CoffeeMaker");

                        await SaveRoom((Guid)accommodationId, roomType, amenities);
                    }

                    break;
            }

            return RedirectToAction("ManageRooms", new { id = accommodationId });
        }

        private async Task SaveRoom(Guid accommodationId, string roomType, List<Amenity> amenities)
        {
            Room room = new()
            {
                AccommodationId = accommodationId,
                RoomType = (RoomTypes)Enum.Parse(typeof(RoomTypes), roomType, true),
                Amenities = amenities
            };

            await _context.Rooms.AddAsync(room);
            await _context.SaveChangesAsync();
        }

        private static void AddAmenityIfChecked(List<Amenity> amenities, string amenity, string name)
        {
            if (amenity != null && amenity.Equals("on"))
            {
                amenities.Add(new Amenity { AmenityType = (AmenityTypes)Enum.Parse(typeof(AmenityTypes), name, true) });
            }
        }

        private static void AddMultipleAmenities(List<Amenity> amenities, string amenityNb, string name)
        {
            if (amenityNb != null)
            {
                for (int i = 0; i < int.Parse(amenityNb); i++)
                {
                    amenities.Add(new Amenity { AmenityType = (AmenityTypes)Enum.Parse(typeof(AmenityTypes), name, true) });
                }
            }
        }

        // GET: Accommodation/DeletePicture/5
        [Route("Accommodation/DeleteRoom/{id}")]
        public async Task<IActionResult> DeleteRoom(Guid id, Guid accommodationId)
        {
            // TODO: Check if user own the picture
            var room = await _context.Rooms.FindAsync(id);

            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();

            return RedirectToAction("ManageRooms", new { id = accommodationId });
        }
    }
}

Views/Accommodation/Delete.cshtml
@model BookingApp.Models.Accommodation

@{
    ViewData["Title"] = "Suppression Logement";
}

<div class="card main-card">
    <div class="card-header">
        <h3>Logement - Suppression</h3>
    </div>

    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Type)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />

            <div class="text-center">
                <input type="submit" value="Supprimer" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-outline-secondary">Retour au CRUD</a>
            </div>
        </form>
    </div>
</div>

Views/Accommodation/Details.cshtml
@model BookingApp.Models.Accommodation

@{
    ViewData["Title"] = "Détails Logement";
}


<div class="card main-card">
    <div class="card-header">
        <h3>Logement - Détails</h3>
    </div>

    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.User)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.User.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Type)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Model.Address
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.HouseRules)
            </dt>
            <dd class="col-sm-10">
                @Model.HouseRules
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Pictures)
            </dt>
            <dd class="col-sm-10">
                @if (Model.Pictures.Count != 0)
                {
                    <div class="row row-cols-1 row-cols-md-4 g-4">

                        @foreach (var item in Model.Pictures)
                        {

                            <div class="col">
                                <div class="card">
                                    <a href="~/upload/@Html.DisplayFor(modelItem => item.FileName)" target="_blank">
                                        <img src="~/upload/@Html.DisplayFor(modelItem => item.FileName)" class="card-img-top"
                                             style="object-fit: cover; width: 100%; height: 11em;">
                                    </a>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <p>Aucune photo ajoutée</p>
                }
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rooms)
            </dt>
            <dd class="col-sm-10">
                @if (Model.Rooms.Count != 0)
                {
                    foreach (var item in Model.Rooms)
                    {
                        <div class="card" style="margin-bottom:1em;">
                            <div class="card-body">
                                @{ var iconSrc = item.RoomType.ToString().ToLower() + ".svg"; }

                                <h5 class="card-title">
                                    <img src="~/svg/@iconSrc" alt="Room icon" height="20px" width="20px" style="vertical-align: -3px;" />
                                    @TypeTranslate.ToFr(Enum.GetName(typeof(RoomTypes), item.RoomType))
                                </h5>

                                <div class="card-text">
                                    <b>Équipements: </b>
                                    @item.AmenitiesStr()

                                    <form asp-action="ManageAmenities" asp-controller="Amenity" asp-route-roomId="@item.Id" method="get" style="display: inline-block;">
                                        <button style="background: none; padding: 0; border: none;" type="submit">
                                            <i class="bi bi-pencil-fill" style="color:orange; padding-left: 0.5em"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>Aucune pièce ajoutée</p>
                }
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Offers)
            </dt>

            <dd class="col-sm-10">
                @if (Model.Offers.Count != 0)
                {

                    <table class="table">
                        <tr>
                            <th>Date d'ajout</th>
                            <th>Début disponibilité</th>
                            <th>Fin disponibilité</th>
                            <th>Prix / Nuit</th>
                            <th>Frais de ménage</th>
                        </tr>
                        @foreach (var item in Model.Offers)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AddingDateTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartAvailability)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EndAvailability)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PricePerNight)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CleaningFee)
                                </td>
                            </tr>
                        }
                    </table>
                }
                else
                {
                    <p>Aucune offre ajoutée</p>
                }
            </dd>

        </dl>

        <div class="text-center">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edition</a>
            <a asp-action="Index" class="btn btn-outline-secondary">Retour au CRUD</a>
        </div>
    </div>
</div>

Views/Accommodation/Edit.cshtml
@model BookingApp.Models.Accommodation

@{
    ViewData["Title"] = "Edition Logement";
}

<div class="card text-center main-card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs nav-fill">
            <li class="nav-item">
                <a class="nav-link active" aria-current="true" href="#">Informations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Picture" asp-action="ManagePictures" asp-route-id="@Model.Id">
                    Photos
                    @if (Model.Pictures != null && Model.Pictures.Count == 0)
                    {
                        <span class="badge rounded-pill bg-danger" title="Vous devez ajouter au moins 1 photo !">!</span>
                    }
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Room" asp-action="ManageRooms" asp-route-id="@Model.Id">
                    Pièces
                    @if (Model.Rooms != null && Model.Rooms.Count == 0)
                    {
                        <span class="badge rounded-pill bg-danger" title="Vous devez ajouter au moins 1 pièce !">!</span>
                    }
                </a>
            </li>
        </ul>
    </div>

    <form asp-action="Edit">
        <div class="card-body text-start">

            <h5>Informations générales :</h5>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Address.Id" />
            <input type="hidden" asp-for="HouseRules.Id" />

            <div class="row form-group">
                <div class="col-md-7">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" placeholder="Studio entier à Paris avec vue sur le Jardin de Tuileries" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="col-md-3">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" class="form-control form-select">
                        <option value="Appartement">Appartement</option>
                        <option value="Maison">Maison</option>
                        <option value="Chambre dans un appartement">Chambre dans un appartement</option>
                        <option value="Chambre dans une maison">Chambre dans une maison</option>
                    </select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>

                <div class="col-md-2">
                    <label asp-for="MaxTraveler" class="control-label"></label>
                    <input asp-for="MaxTraveler" class="form-control" min="1" step="1" placeholder="2" />
                    <span asp-validation-for="MaxTraveler" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <hr class="solid">
            <h5>Adresse :</h5>

            <div class="row form-group">
                <div class="col-md-7">
                    <label asp-for="Address.StreetAndNumber" class="control-label"></label>
                    <input asp-for="Address.StreetAndNumber" class="form-control" placeholder="92 Boulevard de Prague" />
                    <span asp-validation-for="Address.StreetAndNumber" class="text-danger"></span>
                </div>

                <div class="col-md-5">
                    <label asp-for="Address.Complement" class="control-label"></label>
                    <input asp-for="Address.Complement" class="form-control" placeholder="Appartement 116" />
                    <span asp-validation-for="Address.Complement" class="text-danger"></span>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6">
                    <label asp-for="Address.City" class="control-label"></label>
                    <input asp-for="Address.City" class="form-control" placeholder="Paris" />
                    <span asp-validation-for="Address.City" class="text-danger"></span>
                </div>

                <div class="col-md-2">
                    <label asp-for="Address.PostalCode" class="control-label"></label>
                    <input asp-for="Address.PostalCode" class="form-control" placeholder="75001" />
                    <span asp-validation-for="Address.PostalCode" class="text-danger"></span>
                </div>

                <div class="col-md-4">
                    <label asp-for="Address.Country" class="control-label"></label>
                    <input asp-for="Address.Country" class="form-control" placeholder="France" />
                    <span asp-validation-for="Address.Country" class="text-danger"></span>
                </div>
            </div>

            <hr class="solid">
            <h5>Règlement intérieur :</h5>

            <div class="row form-group">
                <div class="col">
                    <label asp-for="HouseRules.ArrivalHour" class="control-label"></label>
                    <input asp-for="HouseRules.ArrivalHour" type="time" class="form-control">
                    <span asp-validation-for="HouseRules.ArrivalHour" class="text-danger"></span>
                </div>

                <div class="col">
                    <label asp-for="HouseRules.DepartureHour" class="control-label"></label>
                    <input asp-for="HouseRules.DepartureHour" type="time" class="form-control">
                    <span asp-validation-for="HouseRules.DepartureHour" class="text-danger"></span>
                </div>
            </div>

            <div class="form-check form-check-inline">
                <input asp-for="HouseRules.PetAllowed" type="checkbox" class="form-check-input">
                <label asp-for="HouseRules.PetAllowed" class="form-check-label"></label>
            </div>
            <div class="form-check form-check-inline">
                <input asp-for="HouseRules.PartyAllowed" type="checkbox" class="form-check-input">
                <label asp-for="HouseRules.PartyAllowed" class="form-check-label"></label>
            </div>
            <div class="form-check form-check-inline">
                <input asp-for="HouseRules.SmokeAllowed" type="checkbox" class="form-check-input">
                <label asp-for="HouseRules.SmokeAllowed" class="form-check-label"></label>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Sauvegarder" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-outline-secondary">Retour au CRUD</a>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}