Controllers/HomeController.cs
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;

namespace BookingApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppContextDB _context;

        public HomeController(AppContextDB context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var appContextDB = _context.Offers
                .Include(o => o.Accommodation)
                .Include(o => o.Accommodation.Address)
                .Include(o => o.Accommodation.User)
                .Include(o => o.Accommodation.Pictures);

            return View(await appContextDB.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Search(string city, string arrivalDate, string departureDate, string nbPerson)
        {
            HttpClient client = new();

            string path = this.Request.Scheme + "://" + this.Request.Host.Value + "/api/advancedsearch/" + city + "/" + arrivalDate + "/" + departureDate + "/" + nbPerson;
            Debug.WriteLine("Search API path: " + path);

            IEnumerable<Offer> offers = null;

            HttpResponseMessage response = await client.GetAsync(path);

            if (response.IsSuccessStatusCode)
            {
                offers = JsonConvert.DeserializeObject<IEnumerable<Offer>>(await response.Content.ReadAsStringAsync());

                ViewBag.Search = true;
            }

            return View("Index", offers);
        }
    }
}

Controllers/OfferController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BookingApp.Controllers
{
    [Authorize(Roles = "Admin,Host")]
    public class OfferController : Controller
    {
        private readonly AppContextDB _context;
        private readonly UserManager<User> _userManager;

        public OfferController(AppContextDB context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Offer
        public async Task<IActionResult> Index()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                return View(await _context.Offers
                    .Include(o => o.Accommodation).ToListAsync());
            }
            else
            {
                return View(await _context.Offers
                    .Include(o => o.Accommodation)
                    .Where(o => o.Accommodation.UserId == user.Id).ToListAsync());
            }
        }

        // GET: Offer/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // GET: Offer/Create
        public async Task<IActionResult> Create()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Name");
            }
            else
            {
                ViewData["AccommodationId"] = new SelectList(_context.Accommodations.Where(a => a.UserId == user.Id), "Id", "Name");
            }

            return View();
        }

        // POST: Offer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("AccommodationId, StartAvailability, EndAvailability, PricePerNight, CleaningFee")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Id", offer.AccommodationId);
            return View(offer);
        }

        // GET: Offer/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) { return NotFound(); }

            var offer = await _context.Offers.FindAsync(id);

            if (offer == null) { return NotFound(); }

            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, 
            [Bind("Id, AccommodationId, StartAvailability, EndAvailability, PricePerNight, CleaningFee")] Offer offer)
        {
            if (id != offer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Get offer's adding date
                offer.AddingDateTime = await _context.Offers.Where(o => o.Id == id).Select(o => o.AddingDateTime).SingleOrDefaultAsync();

                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Id", offer.AccommodationId);
            return View(offer);
        }

        // GET: Offer/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var offer = await _context.Offers.FindAsync(id);
            _context.Offers.Remove(offer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(Guid id)
        {
            return _context.Offers.Any(e => e.Id == id);
        }

        // GET: Offer/View/5
        [AllowAnonymous]
        public async Task<IActionResult> View(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .Include(o => o.Accommodation.Address)
                .Include(o => o.Accommodation.HouseRules)
                .Include(o => o.Accommodation.Pictures)
                .Include(o => o.Accommodation.Rooms)
                .ThenInclude(r => r.Amenities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (offer == null)
            {
                NotFound($"Unable to load offer with ID '{id}'.");
            }

            var userId = _userManager.GetUserId(User);

            if (userId != null && BookmarkExist(offer.Id, userId))
            {
                ViewBag.Bookmark = true;
            } 
            else if (userId != null)
            {
                ViewBag.Bookmark = false;
            }

            if (TempData["AlertType"] != null && TempData["AlertMsg"] != null)
            {
                ViewBag.AlertType = TempData["AlertType"];
                ViewBag.AlertMsg = TempData["AlertMsg"];
            }

            return View(offer);
        }

        public async Task<IActionResult> AddBookmark(Guid id)
        {
            await new BookmarkController(_context, _userManager.GetUserId(User)).Add(id);

            TempData["AlertType"] = "success";
            TempData["AlertMsg"] = "Offre ajoutée aux favoris avec succès ! <a href=\"/Identity/Account/Manage/Bookmark\">Accédez à vos favoris</a>";

            return RedirectToAction("View", new { id });
        }

        public async Task<IActionResult> DeleteBookmark(Guid id)
        {
            await new BookmarkController(_context, _userManager.GetUserId(User)).Delete(id);

            TempData["AlertType"] = "warning";
            TempData["AlertMsg"] = "Offre supprimée des favoris avec succès ! <a href=\"/Identity/Account/Manage/Bookmark\">Accédez à vos favoris</a>";

            return RedirectToAction("View", new { id });
        }

        private bool BookmarkExist(Guid offerId, string userId)
        {
            return _context.Bookmark.Any(b => b.OfferId == offerId && b.UserId == userId);
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<BookingApp.Models.Offer>

@{
    ViewData["Title"] = "Home";
}

<style>
    #mainContainer {
        padding: 0;
        max-width: 100%;
    }

    main.pb-3 {
        padding-bottom: 0em !important;
    }
</style>

<div class="container-fluid px-1 px-sm-4 mx-auto"
     @{String background_url = "/image/background" + new Random().Next(1, 9) + ".jpg";}
     style="background-image: url('@background_url');
     background-size: cover; background-position: center; width: 100%; height: auto; padding-top: 12em; padding-bottom: 10em; padding-left: 2em; padding-right:2em;">

    <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-lg-9 col-xl-8">
            <div class="card shadow-lg p-3 mb-5 rounded">
                <div class="card-header bg-white">
                    <h4 class="mb-1">Trouvez l'hébergement de vos rêves</h4>
                    <small class="text-muted">Du gîte champêtre cosy à l'appartement citadin design</small>
                </div>

                <form asp-action="Search" method="get">
                    <div class="row g-3">
                        <div class="col-md-3">
                            <label style="margin: 0.2em;">Ville</label>
                            <input type="text" class="form-control" name="city" placeholder="Où allez-vous ?" required>
                        </div>

                        <div class="col-md-3">
                            <label style="margin: 0.2em;">Arrivée</label>
                            <input type="date" class="form-control" name="arrivalDate" min="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                        </div>

                        <div class="col-md-3">
                            <label style="margin: 0.2em;">Départ</label>
                            <input type="date" class="form-control" name="departureDate" min="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                        </div>

                        <div class="col-md-2">
                            <label style="margin: 0.2em;">Voyageurs</label>
                            <input type="number" min="1" step="1" class="form-control" name="nbPerson" placeholder="1" required>
                        </div>

                        <div class="col-md-1 d-grid gap-2">
                            <label> </label>
                            <button type="submit" class="btn btn-success"><span class="bi bi-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="album py-5 bg-light">
    <div class="container">

        @if (ViewBag.Search == null)
        {
            <h2>Dernières offres publiées</h2>
        }
        else
        {
            <h2>Offres correspondantes à votre recherche</h2>
        }

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="margin-top: 1em;">

            @if (Model != null)
            {
                int offerNb = 0;

                foreach (var item in Model)
                {
                    <div class="col">
                        <div class="card shadow-sm">
                            <div id="carousel-offer-@offerNb" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                    @for (int i = 0; i < item.Accommodation.Pictures.Count; i++)
                                    {
                                        <button type="button" data-bs-target="#carousel-offer-@offerNb" data-bs-slide-to="@i"
                                                @if (i == 0) { @: class="active" aria-current="true"
                                                } aria-label="Slide @i"></button>
                                    }
                                </div>

                                <div class="carousel-inner">
                                    @{ var firstImg = true;
                                        foreach (Picture picture in item.Accommodation.Pictures)
                                        {
                                            <div class="carousel-item @if (firstImg) {
                                            @:active
                                            firstImg = false; }">
                                                <img src="~/upload/@picture.FileName" class="d-block w-100 card-img-top" style="object-fit: cover; width: 100%; height: 15em;" alt="">
                                            </div>
                                        }
                                    }
                                </div>

                                <button class="carousel-control-prev" type="button" data-bs-target="#carousel-offer-@offerNb" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carousel-offer-@offerNb" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>

                            <div class="card-body">
                                <a asp-controller="Offer" asp-action="View" asp-route-id="@item.Id.ToString()" style="color: black; text-decoration: none;">
                                    <h4 class="mb-1">@item.Accommodation.Address.ShortAddress()</h4>
                                </a>

                                <p class="card-text">
                                    Déposée par
                                    @Html.DisplayFor(modelItem => item.Accommodation.User.FirstName) @Html.DisplayFor(modelItem => item.Accommodation.User.LastName)
                                </p>

                                <p>Disponible du @Html.DisplayFor(modelItem => item.StartAvailability) au @Html.DisplayFor(modelItem => item.EndAvailability)</p>

                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a asp-controller="Offer" asp-action="View" asp-route-id="@item.Id.ToString()" class="btn btn-sm btn-outline-secondary">
                                            Voir l'offre
                                        </a>
                                    </div>

                                    <small class="text-success" style="font-weight: bold;">@Html.DisplayFor(modelItem => item.PricePerNight) €/Nuit</small>
                                </div>
                            </div>
                        </div>
                    </div>

                    offerNb++;
                }
            }
        </div>
    </div>
</div>