Models/Offer.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookingApp.Models
{
    public class Offer
    {
		public Guid Id { get; set; }

		//private User user;

		public Guid AccommodationId { get; set; }
		[Display(Name = "Logement")]
		public virtual Accommodation Accommodation { get; set; }

		[Display(Name = "Date d'ajout")]
		[DataType(DataType.DateTime)]
		public DateTime AddingDateTime { get; set; }

		[Display(Name = "Début disponibilité")]
		[DataType(DataType.Date)]
		public DateTime StartAvailability { get; set; }

		[Display(Name = "Fin disponibilité")]
		[DataType(DataType.Date)]
		public DateTime EndAvailability { get; set; }

		[Display(Name = "Prix par nuit")]
		public double PricePerNight { get; set; }

		[Display(Name = "Frais de ménage")]
		public double CleaningFee { get; set; }

		public Offer()
        {
			this.AddingDateTime = DateTime.Now;
        }
	}
}

Controllers/BookingController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BookingApp.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly AppContextDB _context;
        private readonly UserManager<User> _userManager;

        public BookingController(AppContextDB context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Booking
        public async Task<IActionResult> Index()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            ViewBag.ReturnAction = "Index";

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                return View(await _context.Booking
                    .Include(b => b.Offer).Include(b => b.User).Include(b => b.Offer.Accommodation).ToListAsync());
            }
            else
            {
                return View(await _context.Booking
                    .Where(b => b.UserId == user.Id)
                    .Include(b => b.Offer).Include(b => b.User).Include(b => b.Offer.Accommodation).ToListAsync());
            }
        }

        // GET: Booking/HostIndex
        [Authorize(Roles = "Host, Admin")]
        public async Task<IActionResult> HostIndex()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            ViewBag.ReturnAction = "HostIndex";

            return View("Index", await _context.Booking
                .Include(b => b.Offer).Include(b => b.User).Include(b => b.Offer.Accommodation)
                .Where(b => b.Offer.Accommodation.UserId == user.Id).ToListAsync());
        }


        // POST: Booking/Details/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(Guid id, string returnAction)
        {
            var booking = await _context.Booking
                .Include(b => b.Offer)
                .Include(b => b.User)
                .Include(b => b.Offer.Accommodation)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (booking == null)
            {
                return NotFound();
            }

            ViewBag.ReturnAction = returnAction;

            return View(booking);
        }

        // POST: Booking/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("OfferId, ArrivalDate, ArrivalTime, DepartureDate, DepartureTime, NbPerson")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                int nbNight = (booking.DepartureDate - booking.ArrivalDate).Days;
                double pricePerNight = await _context.Offers.Where(o => o.Id == booking.OfferId).Select(o => o.PricePerNight).SingleOrDefaultAsync();
                double cleaningFee = await _context.Offers.Where(o => o.Id == booking.OfferId).Select(o => o.CleaningFee).SingleOrDefaultAsync();

                User senderUser = await _userManager.GetUserAsync(User);
                User receiverUser = await _context.Offers.Where(o => o.Id == booking.OfferId).Select(o => o.Accommodation.User).SingleOrDefaultAsync();

                // Calcul total price
                double totalPrice = pricePerNight * (double)nbNight + cleaningFee;

                if (await new TransactionController(_context).DoTransaction(senderUser, receiverUser, totalPrice))
                {
                    booking.TotalPrice = totalPrice;
                    booking.UserId = (await _userManager.GetUserAsync(User)).Id;

                    _context.Add(booking);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    TempData["AlertType"] = "danger";
                    TempData["AlertMsg"] = "Vous n'avez pas le montant nécessaire pour procéder à la réservation, il vous manque " +  (totalPrice-senderUser.Balance) + " € ! Veuillez <a href=\"/Identity/Account/Manage/Wallet\">créditer votre compte</a>";

                    return RedirectToAction("View", "Offer", new { id = booking.OfferId });
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/OfferController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingApp.Data;
using BookingApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BookingApp.Controllers
{
    [Authorize(Roles = "Admin,Host")]
    public class OfferController : Controller
    {
        private readonly AppContextDB _context;
        private readonly UserManager<User> _userManager;

        public OfferController(AppContextDB context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Offer
        public async Task<IActionResult> Index()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                return View(await _context.Offers
                    .Include(o => o.Accommodation).ToListAsync());
            }
            else
            {
                return View(await _context.Offers
                    .Include(o => o.Accommodation)
                    .Where(o => o.Accommodation.UserId == user.Id).ToListAsync());
            }
        }

        // GET: Offer/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // GET: Offer/Create
        public async Task<IActionResult> Create()
        {
            User user = await _userManager.GetUserAsync(User);

            if (user == null) { return NotFound(); }

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Name");
            }
            else
            {
                ViewData["AccommodationId"] = new SelectList(_context.Accommodations.Where(a => a.UserId == user.Id), "Id", "Name");
            }

            return View();
        }

        // POST: Offer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("AccommodationId, StartAvailability, EndAvailability, PricePerNight, CleaningFee")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Id", offer.AccommodationId);
            return View(offer);
        }

        // GET: Offer/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) { return NotFound(); }

            var offer = await _context.Offers.FindAsync(id);

            if (offer == null) { return NotFound(); }

            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, 
            [Bind("Id, AccommodationId, StartAvailability, EndAvailability, PricePerNight, CleaningFee")] Offer offer)
        {
            if (id != offer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Get offer's adding date
                offer.AddingDateTime = await _context.Offers.Where(o => o.Id == id).Select(o => o.AddingDateTime).SingleOrDefaultAsync();

                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccommodationId"] = new SelectList(_context.Accommodations, "Id", "Id", offer.AccommodationId);
            return View(offer);
        }

        // GET: Offer/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var offer = await _context.Offers.FindAsync(id);
            _context.Offers.Remove(offer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(Guid id)
        {
            return _context.Offers.Any(e => e.Id == id);
        }

        // GET: Offer/View/5
        [AllowAnonymous]
        public async Task<IActionResult> View(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Accommodation)
                .Include(o => o.Accommodation.Address)
                .Include(o => o.Accommodation.HouseRules)
                .Include(o => o.Accommodation.Pictures)
                .Include(o => o.Accommodation.Rooms)
                .ThenInclude(r => r.Amenities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (offer == null)
            {
                NotFound($"Unable to load offer with ID '{id}'.");
            }

            var userId = _userManager.GetUserId(User);

            if (userId != null && BookmarkExist(offer.Id, userId))
            {
                ViewBag.Bookmark = true;
            } 
            else if (userId != null)
            {
                ViewBag.Bookmark = false;
            }

            if (TempData["AlertType"] != null && TempData["AlertMsg"] != null)
            {
                ViewBag.AlertType = TempData["AlertType"];
                ViewBag.AlertMsg = TempData["AlertMsg"];
            }

            return View(offer);
        }

        public async Task<IActionResult> AddBookmark(Guid id)
        {
            await new BookmarkController(_context, _userManager.GetUserId(User)).Add(id);

            TempData["AlertType"] = "success";
            TempData["AlertMsg"] = "Offre ajoutée aux favoris avec succès ! <a href=\"/Identity/Account/Manage/Bookmark\">Accédez à vos favoris</a>";

            return RedirectToAction("View", new { id });
        }

        public async Task<IActionResult> DeleteBookmark(Guid id)
        {
            await new BookmarkController(_context, _userManager.GetUserId(User)).Delete(id);

            TempData["AlertType"] = "warning";
            TempData["AlertMsg"] = "Offre supprimée des favoris avec succès ! <a href=\"/Identity/Account/Manage/Bookmark\">Accédez à vos favoris</a>";

            return RedirectToAction("View", new { id });
        }

        private bool BookmarkExist(Guid offerId, string userId)
        {
            return _context.Bookmark.Any(b => b.OfferId == offerId && b.UserId == userId);
        }
    }
}

Views/Offer/Create.cshtml
@model BookingApp.Models.Offer

@{
    ViewData["Title"] = "Création Offre";
}

<div class="card main-card">
    <div class="card-header">
        <h3>Offre - Création</h3>
    </div>

    <div class="card-body">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row form-group">
                <div class="col-md-6">
                    <label asp-for="AccommodationId" class="control-label">Logement</label>
                    <select asp-for="AccommodationId" class="form-select" asp-items="ViewBag.AccommodationId"></select>
                </div>

                <div class="col-md-3">
                    <label asp-for="PricePerNight" class="control-label"></label>
                    <div class="input-group mb-3">
                        <input asp-for="PricePerNight" class="form-control" placeholder="20"/>
                        <span class="input-group-text">€</span>
                    </div>
                    <span asp-validation-for="PricePerNight" class="text-danger"></span>
                </div>

                <div class="col-md-3">
                    <label asp-for="CleaningFee" class="control-label"></label>
                    <div class="input-group mb-3">
                        <input asp-for="CleaningFee" class="form-control" placeholder="25"/>
                        <span class="input-group-text">€</span>
                    </div>
                    <span asp-validation-for="CleaningFee" class="text-danger"></span>
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <label asp-for="StartAvailability" class="control-label"></label>
                    <input asp-for="StartAvailability" class="form-control" />
                    <span asp-validation-for="StartAvailability" class="text-danger"></span>
                </div>

                <div class="col">
                    <label asp-for="EndAvailability" class="control-label"></label>
                    <input asp-for="EndAvailability" class="form-control" />
                    <span asp-validation-for="EndAvailability" class="text-danger"></span>
                </div>
            </div>

            <div class="text-center">
                <input type="submit" value="Créer" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-outline-secondary">Retour au CRUD</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Offer/Delete.cshtml
@model BookingApp.Models.Offer

@{
    ViewData["Title"] = "Suppression Offre";
}


<div class="card main-card">
    <div class="card-header">
        <h3>Offre - Suppression</h3>
    </div>

    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Accommodation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Accommodation.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AddingDateTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AddingDateTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartAvailability)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartAvailability)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EndAvailability)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EndAvailability)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PricePerNight)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PricePerNight)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CleaningFee)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CleaningFee)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />

            <div class="text-center">
                <input type="submit" value="Supprimer" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-outline-secondary">Retour au CRUD</a>
            </div>
        </form>

    </div>
</div>

Views/Offer/View.cshtml
@model BookingApp.Models.Offer

@{
    ViewData["Title"] = "Details";
}

<div style="padding-top: 0.5em">
    <partial name="_StatusMessage" />
</div>

<div class="card main-card-0_5">

    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            @for (int i = 0; i < Model.Accommodation.Pictures.Count; i++)
            {
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i"
                        @if (i == 0) { @: class="active" aria-current="true"
                        } aria-label="Slide @i"></button>
            }
        </div>

        <div class="carousel-inner">
            @{ var firstImg = true;
                foreach (Picture picture in Model.Accommodation.Pictures)
                {
                        <div class="carousel-item @if (firstImg) {
                        @:active
                        firstImg = false; }">

                            <a href="~/upload/@picture.FileName" target="_blank">
                                <img src="~/upload/@picture.FileName" class="d-block w-100 card-img-top" style="object-fit: cover; width: 100%; height: 450px;" alt="">
                            </a>
                        </div>
                }
            }
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="card-body">

        <div class="container">
            <div class="row">

                <div class="col-sm-8">
                    <div class="row align-items-center">

                        <div class="col">
                            <h3>@Model.Accommodation.Name</h3>
                        </div>

                        <div class="col-auto">
                            @if (ViewBag.Bookmark != null)
                            {
                                if (!ViewBag.Bookmark)
                                {
                                    <form asp-action="AddBookmark" style="display: inline-block;">
                                        <input type="hidden" asp-for="@Model.Id" />

                                        <button style="background: none; padding: 0px; border: none;" type="submit">
                                            <h3><i class="bi bi-bookmark-plus" style="color:black;"></i></h3>
                                        </button>
                                    </form>
                                }
                                else
                                {
                                    <form asp-action="DeleteBookmark" style="display: inline-block;">
                                        <input type="hidden" asp-for="@Model.Id" />

                                        <button style="background: none; padding: 0px; border: none;" type="submit">
                                            <h3><i class="bi bi-bookmark-x-fill" style="color:black;"></i></h3>
                                        </button>
                                    </form>
                                }
                            }
                        </div>
                    </div>

                    <hr class="solid">

                    <div class="d-grid gap-1">
                        <div class="p-1">
                            <h5 style="display:inline;"><i class="bi bi-house-door" style="vertical-align: -1px;"></i></h5>
                            <h6 style="display:inline;">@Model.Accommodation.Type</h6>
                        </div>

                        <div class="p-1">
                            <h5 style="display:inline;"><i class="bi bi-geo-alt" style="vertical-align: -2px;"></i></h5>
                            <h6 style="display:inline;">@Model.Accommodation.Address.ShortAddress()</h6>
                        </div>

                        <div class="p-1">
                            <h5 style="display:inline;"><i class="bi bi-person" style="vertical-align: -1px;"></i></h5>
                            <h6 style="display:inline;">@Model.Accommodation.MaxTraveler voyageur(s) maximum</h6>
                        </div>

                        <div class="p-1">
                            <h5 style="display:inline;"><i class="bi bi-file-text" style="vertical-align: -2px;"></i></h5>
                            <p class="card-text" style="display:inline;">@Model.Accommodation.Description</p>
                        </div>
                    </div>

                    <hr class="solid">

                    <h4>Pièce(s) [@Model.Accommodation.Rooms.Count] :</h4>

                    @foreach (var item in Model.Accommodation.Rooms)
                    {
                        <div class="card" style="margin-bottom:1em;">
                            <div class="card-body">
                                @{ string iconSrc = item.RoomType.ToString().ToLower() + ".svg"; }

                                <h5 class="card-title">
                                    <img src="~/svg/@iconSrc" alt="Room icon" height="20px" width="20px" style="vertical-align: -3px;" />
                                    @TypeTranslate.ToFr(Enum.GetName(typeof(RoomTypes), item.RoomType))
                                </h5>

                                <p class="card-text">
                                    <b>Équipements: </b>
                                    @item.AmenitiesStr()
                                </p>
                            </div>
                        </div>
                    }

                    <hr class="solid">

                    <h4>Règlement du logement :</h4>

                    <div class="d-grid gap-1">
                        <div class="p-1">
                            <img src="~/svg/clock.svg" alt="Clock icon" height="20px" width="20px" style="vertical-align: -4px; margin-right:3px;" />
                            <h6 style="display:inline;">
                                Heure d'arrivée : Après @Model.Accommodation.HouseRules.ArrivalHour.ToString("hh\\hmm") - Heure de départ : Avant @Model.Accommodation.HouseRules.DepartureHour.ToString("hh\\hmm")
                            </h6>
                        </div>

                        <div class="p-1">
                            <img src="~/svg/pet.svg" alt="Pet icon" height="20px" width="20px" style="vertical-align: -4px; margin-right:3px;" />
                            <h6 style="display:inline;">Animaux autorisés : @(Model.Accommodation.HouseRules.PetAllowed ? "Oui" : "Non")</h6>
                        </div>

                        <div class="p-1">
                            <img src="~/svg/party.svg" alt="Party icon" height="20px" width="20px" style="vertical-align: -4px; margin-right:3px;" />
                            <h6 style="display:inline;">Fêtes autorisées : @(Model.Accommodation.HouseRules.PartyAllowed ? "Oui" : "Non")</h6>
                        </div>

                        <div class="p-1">
                            <img src="~/svg/smoke.svg" alt="Smoke icon" height="20px" width="20px" style="vertical-align: -4px; margin-right:3px;" />
                            <h6 style="display:inline;">Logement fumeur : @(Model.Accommodation.HouseRules.SmokeAllowed ? "Oui" : "Non")</h6>
                        </div>
                    </div>

                </div>

                <div class="col-sm-4">
                    <div class="card shadow p-3 mb-5 bg-body rounded">
                        <div class="card-header">
                            <h5 class="card-title">Réservation</h5>
                        </div>
                        <div class="card-body">

                            <div class="d-grid gap-1">
                                <div class="p-1">
                                    <h6 style="display:inline;"><i class="bi bi-cash"></i></h6>
                                    <h6 style="display:inline;">Prix par nuit : @Model.PricePerNight €</h6>
                                </div>

                                <div class="p-1">
                                    <h6 style="display:inline;"><i class="bi bi-bucket"></i></h6>
                                    <h6 style="display:inline;">Frais de ménage : @Model.CleaningFee €</h6>
                                </div>
                            </div>

                            <hr class="solid">

                            <p class="card-text">Sélectionnez vos dates de réservations :</p>

                            <form asp-controller="Booking" asp-action="Create">
                                <input type="hidden" asp-for="Id" name="OfferId"/>

                                @{ 
                                    var minArrival = (DateTime.Now > Model.StartAvailability ? DateTime.Now : Model.StartAvailability);
                                }

                                <div class="row g-3" style="margin-bottom: 0.5em;">
                                    <div class="col col-md-7">
                                        <label for="inputArrivalDate">Arrivé</label>
                                        <input type="date" class="form-control" id="inputArrivalDate" name="ArrivalDate"
                                               min="@minArrival.ToString("yyyy-MM-dd")" max="@Model.EndAvailability.AddDays(-1).ToString("yyyy-MM-dd")" required>
                                    </div>

                                    <div class="col col-md-5">
                                        <label for="inputArrivalTime">Heure</label>
                                        <input type="time" class="form-control" id="inputArrivalTime" name="ArrivalTime"
                                               min="@Model.Accommodation.HouseRules.ArrivalHour.ToString("hh\\:mm")" max="23:59" required>
                                    </div>
                                </div>

                                <div class="row g-3" style="margin-bottom: 0.5em;">
                                    <div class="col col-md-7">
                                        <label for="inputDepartureDate">Départ</label>
                                        <input type="date" class="form-control" id="inputDepartureDate" name="DepartureDate"
                                               min="@minArrival.AddDays(1).ToString("yyyy-MM-dd")" max="@Model.EndAvailability.ToString("yyyy-MM-dd")" required>
                                    </div>

                                    <div class="col col-md-5">
                                        <label for="inputDepartureTime">Heure</label>
                                        <input type="time" class="form-control" id="inputDepartureTime" name="DepartureTime"
                                               min="00:00" max="@Model.Accommodation.HouseRules.DepartureHour.ToString("hh\\:mm")" required>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="nbPersonSelector">Nombre de voyageur(s)</label>
                                    <select class="form-control form-select" id="nbPersonSelector" name="NbPerson" required>
                                        @for (int i = 1; i <= Model.Accommodation.MaxTraveler; i++)
                                        {
                                            <option>@i</option>
                                        }
                                    </select>
                                </div>

                                <div class="d-grid gap-2">
                                    <button class="btn btn-success" type="submit">Réserver</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>